name: Publish

on:
  workflow_dispatch:
  push:
    branches: ["neo"]

jobs:
  time:
    runs-on: ubuntu-latest
    outputs:
      v: ${{ steps.date.outputs.time }}
      y: ${{ steps.date.outputs.y }}
      md: ${{ steps.date.outputs.md }}
      hm: ${{ steps.date.outputs.hm }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Time
        id: date
        run: |
          echo "::set-output name=time::$(date +'%Y.%m.%d.%H.%M')"
          echo "::set-output name=y::$(date +'%Y')"
          echo "::set-output name=md::$(date +'%m%d')"
          echo "::set-output name=hm::$(date +'%H%M')"
      - name: EchoTime
        run: |
          echo "The current time is: ${{ steps.date.outputs.time }}"
  
  win-x86:
    runs-on: windows-latest
    needs: time
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Time
        id: date
        run: |
          echo "${{ needs.time.outputs.v }}" > ./src/RMCL/RMCL.Desktop/DateTime.txt
          echo "Version is ${{ needs.time.outputs.v }}"
        shell: bash
      - name: Build
        run: |
          cd ./src/RMCL/RMCL.Desktop
          dotnet publish -c Release -r win-x86 /p:PublishSingleFile=true /p:PublishReadyToRun=true /p:IncludeNativeLibrariesForSelfExtract=true /p:SelfContained=false -o "./publish/x86"
      - name: UploadArtifacts
        uses: actions/upload-artifact@v4
        with:
          name: win-artifacts-x86
          path: |
            ./publish/x86/*.exe


  publish:
    needs: [win-x86, time]
    runs-on: ubuntu-latest
    steps:
      - name: Time
        id: gdate
        run: |
          echo "date=$(date +'%Y-%m-%d.%H-%M-%S')" >> $GITHUB_OUTPUT
          echo "title=$(date +'%Y.%m.%d.%H.%M')" >> $GITHUB_OUTPUT

      - name: Download-WindowsArtifacts-x86
        uses: actions/download-artifact@v4
        with:
          name: win-artifacts-x86
          path: ./src/Release/

      - name: List Files
        run: |
          ls -la ./src/Release/
          
      - name: Publish Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.TOKEN }}"
          title: "v${{ needs.time.outputs.v }}"
          automatic_release_tag: "RMCL.Transcend-${{ steps.gdate.outputs.date }}"
          prerelease: false
          files: |
            ./src/Release/*.exe
